backbone: "resnet50"
pretrained: True

loss: "GuidedSelectiveLoss"
partial_loss_mode: 'negative'
gamma_pos: 1
gamma_neg: 2
gamma_unl: 7
gamma_can: 4
alpha_pos: 1
alpha_neg: 1
alpha_unl: 1
alpha_can: 1

fast_lr: 7e-4
base_lr: 1e-5
weight_decay: 1e-4
f_obj_embs: "data/embeddings/onehot_obj_embs_d1763.pth"
d_obj: 1763
num_classes: 591
prior_path: ""
