backbone: "resnet50"
pretrained: True

loss: "GuidedSelectiveLoss"
partial_loss_mode: 'ignore'
gamma_pos: 0
gamma_neg: 0
gamma_unl: 0
gamma_can: 0
alpha_pos: 1
alpha_neg: 1
alpha_unl: 0
alpha_can: 0

fast_lr: 7e-4
base_lr: 1e-5
weight_decay: 1e-4
f_obj_embs: "data/embeddings/onehot_obj_embs_d1763.pth"
d_obj: 1763
num_classes: 591
prior_path: ""